elastic_app/urls.py
from django.conf.urls import url

from .views import CitationList, SearchList, UploadView

app_name = 'citations'
urlpatterns = [
    url(r'^$', CitationList.as_view(), name='citation-list'),
    url(r'^search/$', SearchList.as_view(), name='search'),
    url(r'^upload/$', UploadView.as_view(), name='upload')
]

elastic_endnote/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^citations/', include('elastic_app.urls')),
    url(r'^django-rq/', include('django_rq.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

elastic_app/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete

from .search import Citation as CitationDoc


class Citation(models.Model):
    title = models.CharField(max_length=512)
    keywords = models.CharField(max_length=512)
    journal = models.CharField(max_length=512)
    volume = models.CharField(max_length=200)
    date = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def create_from_record(cls, record):
        return cls(
            title=record['title'],
            keywords=record['keywords'],
            journal=record['journal'],
            volume=record['volume'],
            date=record['date'],
        )

    def to_search(self):
        d = {
            'id': self.pk,
            'title': self.title,
            'journal': self.journal,
            'keywords': [word for word in self.keywords.split(';')],
            'volume': self.volume,
            'date': self.date
        }

        return CitationDoc(
            meta={'id': d['id']},
            **d
        )

    def __str__(self):
        return "{0}. {1} {2}: {3} ({4})".format(
            self.title,
            self.journal,
            self.date,
            self.volume,
            self.keywords
        )


class UploadFailure(models.Model):
    title = models.CharField(max_length=512)
    reason = models.CharField(max_length=512)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Title: {0} -- Reason: {1}".format(
            self.title,
            self.reason
        )


# Register search callbacks
def update_search(instance, **kwargs):
    instance.to_search().save()


def remove_from_search(instance, **kwargs):
    instance.to_search().delete()


post_save.connect(update_search, sender=Citation)
pre_delete.connect(remove_from_search, sender=Citation)

elastic_app/forms.py
from django import forms


class TagsField(forms.MultipleChoiceField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('choices', ())
        super(TagsField, self).__init__(*args, **kwargs)

    def valid_value(self, value):
        return True


class XmlForm(forms.Form):
    docfile = forms.FileField(label='Select a file')


class SearchForm(forms.Form):
    search = forms.CharField(label='Title')
    # keywords = TagsField(required=False)

elastic_app/views.py
import binascii
import django_rq
import os

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.list import ListView
from django.views import View

from .forms import XmlForm, SearchForm
from .jobs import process_upload
from .models import Citation, UploadFailure
from .search import CitationSearch


class CitationList(ListView):
    model = Citation
    paginate_by = 100
    extra_context = {
        'form': SearchForm(),
        'has_failures': UploadFailure.objects.count() > 0
    }

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        for key, value in self.extra_context.items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context


class UploadFailureList(ListView):
    model = UploadFailure
    paginate_by = 100


class SearchList(ListView):
    model = Citation
    form_class = SearchForm
    template_name = 'elastic_app/citation_list.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET)
        citations = []

        if form.is_valid():
            title = request.GET.get('search')
            bs = CitationSearch(title)
            results = bs.execute()
            hits = [hit['_id'] for hit in results['hits']['hits']]
            clauses = ' '.join(
                ['WHEN id=%s THEN %s' % (pk, i) for i, pk in enumerate(hits)]
            )
            ordering = 'CASE %s END' % clauses

            citations = Citation.objects.filter(pk__in=hits).extra(
                select={'ordering': ordering}, order_by=('ordering',)
            )

        return render(
            request,
            self.template_name,
            {
                'object_list': citations,
                'has_failures': UploadFailure.objects.count() > 0,
                'form': form
            }
        )


class UploadView(View):
    form_class = XmlForm
    template_name = 'elastic_app/upload.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            file = request.FILES['docfile']
            self._handle_uploaded_file(file)
            return HttpResponseRedirect(reverse('citations:citation-list'))

        return render(request, self.template_name, {'form': form})

    def _handle_uploaded_file(self, f):
        # TODO: Add S3 support for file storage
        file_path = '/tmp/{}.xml'.format(str(binascii.b2a_hex(os.urandom(15))))
        with open(file_path, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)

        # Enqueue for further processing
        django_rq.enqueue(process_upload, file_path)

elastic_app/templates/elastic_app/base.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>
      Citations
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700,600,800' rel='stylesheet' type='text/css'>
  </head>
  <body class="bg-grey-lighter">
    <div class="container mx-auto">
      {% block "body" %} {% endblock %}
    </div>
  </body>
</html>

elastic_app/templates/elastic_app/citation_list.html
{% extends "elastic_app/base.html" %}

{% block "body" %}
<section>
  <ul>
    <li>
      <a href="{% url 'citations:upload' %}">Upload Citation</a>
    </li>
    {% if has_failures %}
    <li>
      <a href="{% url 'citations:failures' %}">View Failures</a>
    </li>
    {% endif %}
    <li>
      <form action="{% url 'citations:search' %}" method="get" enctype="multipart/form-data">
        {{ form }}
        <p><input type="submit" class="btn btn-primary" value="Go"/></p>
      </form>
    </li>
  </ul>
</section>

{% if page_obj %}
<section>
  <nav>
    <ul class="pagination">
      <li class="page-item {% if page_obj.has_previous %}{{ '' }}{% else %}{{ 'disabled' }}{% endif %}">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="page-link">previous</a>
        {% else %}
          <a href="javascript:;" class="page-link">previous</a>
        {% endif %}
      </li>

      <span class="bg-white border border-left-0 border-right-0 p-1">
        Page {{ page_obj.number }} of {{ paginator.num_pages }}
      </span>

      <li class="page-item {% if page_obj.has_next %}{{ '' }}{% else %}{{ 'disabled' }}{% endif %}">
        {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Next</a>
        {% else %}
        <a class="page-link" href="javascript:;">Next</a>
        {% endif %}
      </li>
    </ul>
  </nav>
</section>
{% endif %}

<section class="mx-auto">
    {% for citation in object_list %}
      <article class="w-full lg:flex shadow mt-4">
        <div class="w-full border-r border-b border-l border-grey-light lg:border-l-0 lg:border-t lg:border-grey-light bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
          <h4 class="card-title">{{ citation.title }}</h4>
          <p class="card-text">{{ citation.journal }}. {{ citation.date }};{{ citation.volume}}</p>
        </div>
      </article>
    {% endfor %}
</section>

{% if page_obj %}
<section>
  <nav>
    <ul class="pagination">
      <li class="page-item {% if page_obj.has_previous %}{{ '' }}{% else %}{{ 'disabled' }}{% endif %}">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="page-link">previous</a>
        {% else %}
          <a href="javascript:;" class="page-link">previous</a>
        {% endif %}
      </li>

      <span class="bg-white border border-left-0 border-right-0 p-1">
        Page {{ page_obj.number }} of {{ paginator.num_pages }}
      </span>

      <li class="page-item {% if page_obj.has_next %}{{ '' }}{% else %}{{ 'disabled' }}{% endif %}">
        {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Next</a>
        {% else %}
        <a class="page-link" href="javascript:;">Next</a>
        {% endif %}
      </li>
    </ul>
  </nav>
</section>
{% endif %}

{% endblock %}

elastic_app/templates/elastic_app/upload.html
{% extends "elastic_app/base.html" %}

{% block "body" %}
<form action="{% url 'citations:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p>{{ form.non_field_errors }}</p>

  <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

  <p>
    {{ form.docfile.errors }}
    {{ form.docfile }}
  </p>

  <p><input type="submit" value="Upload"/></p>
</form>
{% endblock %}

elastic_app/templates/elastic_app/upload_failure_list.html
{% extends "elastic_app/base.html" %}

{% block "body" %}
<div>
  <ul>
    <li>
      <a href="{% url 'citations:index' %}">Home</a>
    </li>
  </ul>
  
  <div class="pagination">
    <span class="step-links">
      {% if failures.has_previous %}
        <a href="?page={{ failures.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ failures.number }} of {{ failures.paginator.num_pages }}.
      </span>

      {% if failures.has_next %}
        <a href="?page={{ failures.next_page_number }}">next</a>
      {% endif %}
    </span>
  </div>

  <ul>
    {% for failure in failures %}
      <li>{{ failure }}</li>
    {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if failures.has_previous %}
        <a href="?page={{ failures.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ failures.number }} of {{ failures.paginator.num_pages }}.
      </span>

      {% if failures.has_next %}
        <a href="?page={{ failures.next_page_number }}">next</a>
      {% endif %}
    </span>
  </div>

</div>
{% endblock %}